Repository bbaegi-six/dondothat-client, pull requests merged in 2025-07, with the labels that each got.

#5 Feat/4
  src/App.vue
  src/components/layout/Nav.vue
  src/pages/home/Home.vue
Labels: enhancement

#12 [FEAT] 로그인, 회원가입 디테일 수정
  src/components/Button.vue
  src/pages/auth/Register.vue
Labels: feat

#29 feat: #28 netlify.toml 파일 생성
  .gitignore
  netlify.toml
Labels: 🐞bugfix

#31 [FEAT] 마이페이지 구현
  src/components/BaseCard.vue
  src/components/Typography.vue
  src/components/layout/Header.vue
  src/components/profile/AccountCard.vue
  src/components/profile/Typography.vue
  src/pages/profile/Completed.vue
  src/pages/profile/ConfirmModal.vue
  src/pages/profile/Edit.vue
  src/pages/profile/Notifications.vue
  src/pages/profile/Policy.vue
  src/pages/profile/Profile.vue
  src/pages/profile/Security.vue
  src/pages/profile/Settings.vue
  src/pages/profile/Terms.vue
  src/router/index.js
  src/stores/profile.js
Labels: ✨feat

#35 [FEAT] 닉네임 변경 페이지 구현
  src/App.vue
  src/components/InputWithButton.vue
  src/pages/profile/Edit.vue
  src/pages/profile/Profile.vue
  src/stores/profile.js
Labels: ✨feat

#43 [FEAT] 챌린지 메인 및 선택페이지 구현
  package-lock.json
  src/pages/challenge/Challenge.vue
  src/pages/challenge/ChallengeDaysInput.vue
  src/pages/challenge/ChallengeFlow.vue
  src/pages/challenge/ChallengeLoading.vue
  src/pages/challenge/ChallengeSelection.vue
  src/router/index.js
Labels: ✨feat
