Repository bbaegi-six/dondothat-client, pull requests merged in 2025-08, with the labels that each got.

#61 [REFACTOR] 프론트엔드 배포 수정
  .env
  .env.development
  .env.preview
  .env.production
  netlify.toml
  src/components/expenses/TransactionCard.vue
  src/pages/expenses/Expenses.vue
  src/router/index.js
  src/services/expensesService.js
  src/stores/expenses.js
  src/utils/api.js
Labels: 🔧refactor

#67 [FEAT] 이전 메시지 불러오기
  src/components/chat/ChatMessage.vue
  src/pages/chat/Chat.vue
  src/router/index.js
  src/services/chatApi.js
  src/stores/chat.js
Labels: ✨feat

#92 [FIX] API url 설정 변경
  src/utils/api.js
Labels: 🐞bugfix

#105 [FEAT] 모달 공통 컴포넌트
  src/components/Modal.vue
Labels: ✨feat

#106 [FEAT] 메인페이지 저금통 여부 조건부 렌더링
  src/pages/home/Home.vue
Labels: ✨feat

#111 [REFACTOR] 내역 페이지에 새로고침 버튼 및 자산연동 후 데이터 로딩
  src/components/layout/Header.vue
  src/pages/account/steps/Step5Complete.vue
  src/pages/expenses/Expenses.vue
  src/pages/home/Home.vue
  src/services/expensesService.js
  src/stores/expenses.js
Labels: 🔧refactor

#108 [FEAT] 네브바 아이콘 활성화 여부 표시
  src/components/layout/Nav.vue
Labels: ✨feat

#129 [FEAT] 챌린지 참여 정보 출력
  src/main.js
  src/pages/challenge/Challenge.vue
  src/pages/challenge/ChallengeFailed.vue
  src/pages/challenge/ChallengeProgress.vue
  src/pages/home/Home.vue
  src/services/challengeService.js
  src/stores/challenge.js
Labels: ✨feat

#134 [FEAT] 챌린지 모달 추가
  src/components/Button.vue
  src/components/Modal.vue
  src/pages/challenge/ChallengeProgress.vue
  src/pages/challenge/ModalFirst.vue
  src/pages/challenge/ModalSecond.vue
  src/pages/challenge/ModalThird.vue
Labels: ✨feat

#142 [FEAT] 메인페이지에 저금 연동 #141
  src/pages/challenge/ChallengeProgress.vue
  src/pages/expenses/Expenses.vue
  src/pages/home/Home.vue
Labels: ✨feat

#163 [FIX] 웹앱 로고 최신버전으로 변경
  public/apple-touch-icon.png
  public/favicon-192x192.png
  public/favicon-512x512.png
Labels: 🐞bugfix

#175 [FIX] 배포 환경에서 채팅 연결 안됨
  src/stores/chat.js
Labels: 🐞bugfix

#197 [REFACTOR] px 단위를 Tailwind CSS로 변환
  src/App.vue
  src/components/account/AccountHeader.vue
  src/components/charts/ExpenseChart.vue
  src/components/chat/ChatInput.vue
  src/components/chat/ChatMessage.vue
  src/components/chat/ChatMessages.vue
  src/components/effects/ConfettiEffect.vue
  src/components/expenses/TransactionCard.vue
  src/components/layout/Header.vue
  src/components/layout/Nav.vue
  src/components/modals/ConfirmModal.vue
  src/components/profile/Challenge.vue
  src/components/sections/ChallengeSection.vue
  src/components/sections/ExpenseSummary.vue
  src/components/sections/SavingAccountSection.vue
  src/components/tier/TierDisplay.vue
  src/components/ui/BaseCard.vue
  src/components/ui/InputWithButton.vue
  src/components/ui/Square.vue
  src/pages/account/Account.vue
  src/pages/account/steps/Step1Welcome.vue
  src/pages/account/steps/Step2BankSelect.vue
  src/pages/account/steps/Step3AccountForm.vue
  src/pages/account/steps/Step4Processing.vue
  src/pages/account/steps/Step5Complete.vue
  src/pages/auth/Login.vue
  src/pages/auth/Register.vue
  src/pages/challenge/Challenge.vue
  src/pages/challenge/ChallengeDaysInput.vue
  src/pages/challenge/ChallengeFailed.vue
  src/pages/challenge/ChallengeFlow.vue
  src/pages/challenge/ChallengeLoading.vue
  src/pages/challenge/ChallengeProgress.vue
  src/pages/challenge/ChallengeSelection.vue
  src/pages/challenge/ConnectSub.vue
  src/pages/chat/Chat.vue
  src/pages/expenses/ExpenseEdit.vue
  src/pages/expenses/Expenses.vue
  src/pages/home/Home.vue
  src/pages/profile/Edit.vue
  src/pages/profile/MyChallenge.vue
  src/pages/profile/Policy.vue
  src/pages/profile/Profile.vue
  src/pages/profile/Terms.vue
  src/services/challengeService.js
Labels: 🔧refactor

#199 [FIX] 채팅 페이지 반응형 수정
  src/components/chat/ChatInput.vue
  src/components/chat/ChatMessage.vue
  src/components/chat/ChatMessages.vue
  src/pages/chat/Chat.vue
  src/pages/chat/NoChat.vue
  src/stores/chat.js
Labels: 🐞bugfix
